
# ワークフロー名
name: test_chatbot

# 発火タイミング
on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install line-bot-sdk
      - name: Run script
        env:
          CHANNEL_ACCESS_TOKEN: "tcHTcxy8mEq0+fkuaxPjIomIPEWUv4KVC264D70ADpUZpmyAUvvs+Gn9sORxMM123QPuX2lnXr8cjzibMJ6Tml0evnfWiWz0gvB3LgLmo93jHN0ZDICzKgEWb95tTFI9dY96d/DwHb9obARRU84kEwdB04t89/1O/w1cDnyilFU="
          USER_ID: "U33b807b0575c2da9234900cd2cb156e3"
        run: |
          # main.pyの実行
          python line_cute.py
